### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by dmatsanganis** [antek16x/Face_Recognize#1]
I download the project today and change its keys but the app cannot recognise images from gallery. Are you sure it still work like you show on the gif-video ?

**Comment by antek16x** [comment]
What region you chose when you created your Face API keys? Because my app
works default on region westus.

czw., 2 wrz 2021 o 19:41 Dimitris Matsanganis ***@***.***>
napisał(a):

**Comment by dmatsanganis** [comment]
Yeah that was the problem I had wrong server. Now it works! Thank you!
________________________________
Από: Bartek ***@***.***>
Στάλθηκε: Παρασκευή, 3 Σεπτεμβρίου 2021 9:40 πμ
Προς: antek16x/Face_Recognize ***@***.***>
Κοιν.: Dimitris Matsanganis ***@***.***>; Author ***@***.***>
Θέμα: Re: [antek16x/Face_Recognize] Still works? (#1)


What region you chose when you created your Face API keys? Because my app
works default on region westus.

czw., 2 wrz 2021 o 19:41 Dimitris Matsanganis ***@***.***>
napisał(a):
